spec:
  template:
    spec:
      containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
            secretKeyRef:
              key: database-user
              name: mariadb
          - name: MYSQL_PASSWORD
            valueFrom:
            secretKeyRef:
              key: database-password
              name: mariadb
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mariadb