spec:
  template:
    spec:
      containers:
       - env:
         - name: SPRING_PROFILES_ACTIVE
           value: rahti
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               key: database-user
               name: mysql
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               key: database-password
               name: mysql
         - name: MYSQL_DATABASE
           valueFrom:
             secretKeyRef:
               key: database-name
               name: mysql
         - name: JWT_SECRET
           valueFrom:
             secretKeyRef:
               key: jwt
               name: jwtsecret
          
     